import { createRequestHandler } from "@react-router/node";

export default async function handler(req, res) {
  // Import the compiled server build generated by `react-router build`
  const build = await import("../build/server/index.js");
  const requestHandler = createRequestHandler({ build });
  return requestHandler(req, res);
}
